//
// Created by diogo on 17/01/2022.
//

#ifndef AED_TRANSPORTESPUBLICOSPORTO_ADMINMENU_H
#define AED_TRANSPORTESPUBLICOSPORTO_ADMINMENU_H


class AdminMenu {

};


#endif //AED_TRANSPORTESPUBLICOSPORTO_ADMINMENU_H
